import type { Metadata } from "next";
import "./globals.css";
import SimpleBottomNavigation from '../components/NavBar'; // Adjust the path if necessary

export const metadata: Metadata = {
  title: "SnapZoska",
  description: "Generated by Vojtech Pukancik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body>
        {children}
        <SimpleBottomNavigation /> {/* Include the bottom navigation */}
      </body>
    </html>
  );
}
