// Import the AuthGuard component, which is responsible for handling authentication logic
import AuthGuard from "@/components/AuthGuard";

// Define metadata for the page
export const metadata = { 
  title: "SnapZoska",
  description: "Generated by Vojtech Pukancik",
};

// Define the PrivateLayout component, which wraps its children with the AuthGuard to ensure only authenticated users can access the content
export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode; // Type annotation specifying that children is a ReactNode (any valid React child element)
}) {
  return <AuthGuard>{children}</AuthGuard>;
}
